/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UnidadV6V;

/**
 *
 * @author Asus
 */
public class FRNBanco extends javax.swing.JFrame {
    Cbanco cuenta[] = new Cbanco[20];
     private int cont=0;
      float pasivo=0;
        float activo=0;
        float capital=0;
    /**
     * Creates new form FRNBanco
     */
    public FRNBanco() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txt_cuenta1 = new javax.swing.JTextField();
        txt_cliente2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_cuenta = new javax.swing.JTextField();
        txt_saldo = new javax.swing.JTextField();
        txt_cliente1 = new javax.swing.JTextField();
        txt_interes = new javax.swing.JTextField();
        btn_asientoContable = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_salida = new javax.swing.JTextArea();
        jbl_error = new javax.swing.JLabel();
        jcb_tipoCuenta = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txt_tipoCliente = new javax.swing.JTextField();
        txt_tipomovi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_balance = new javax.swing.JButton();
        dexc = new javax.swing.JLabel();
        txt_des = new javax.swing.JTextField();
        jbc_te = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txt_tipoCuenta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel4.setText("Cliente:");

        txt_cuenta1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        txt_cuenta1.setForeground(new java.awt.Color(255, 153, 51));

        txt_cliente2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        txt_cliente2.setForeground(new java.awt.Color(255, 153, 51));
        txt_cliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cliente2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Wide Latin", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Sistema contable el zorro");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel2.setText("Cuenta:");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel3.setText("Saldo:");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel5.setText("Cliente:");

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel6.setText("Interes:");

        txt_cuenta.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        txt_cuenta.setForeground(new java.awt.Color(255, 153, 51));
        txt_cuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cuentaActionPerformed(evt);
            }
        });

        txt_saldo.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        txt_saldo.setForeground(new java.awt.Color(255, 153, 51));
        txt_saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_saldoActionPerformed(evt);
            }
        });

        txt_cliente1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        txt_cliente1.setForeground(new java.awt.Color(255, 153, 51));
        txt_cliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cliente1ActionPerformed(evt);
            }
        });

        txt_interes.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        txt_interes.setForeground(new java.awt.Color(255, 153, 51));
        txt_interes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_interesActionPerformed(evt);
            }
        });

        btn_asientoContable.setFont(new java.awt.Font("Yu Gothic", 3, 14)); // NOI18N
        btn_asientoContable.setForeground(new java.awt.Color(255, 153, 0));
        btn_asientoContable.setText("Asiento contable");
        btn_asientoContable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_asientoContableActionPerformed(evt);
            }
        });

        jta_salida.setEditable(false);
        jta_salida.setColumns(20);
        jta_salida.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jta_salida.setRows(5);
        jScrollPane1.setViewportView(jta_salida);

        jbl_error.setFont(new java.awt.Font("Trebuchet MS", 3, 14)); // NOI18N
        jbl_error.setForeground(new java.awt.Color(255, 0, 0));
        jbl_error.setMaximumSize(new java.awt.Dimension(577, 23));

        jcb_tipoCuenta.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jcb_tipoCuenta.setForeground(new java.awt.Color(255, 153, 0));
        jcb_tipoCuenta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Pasivo", "Capital" }));
        jcb_tipoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_tipoCuentaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel7.setText("Tipo de cuenta:");

        txt_tipoCliente.setEditable(false);
        txt_tipoCliente.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        txt_tipoCliente.setForeground(new java.awt.Color(255, 153, 51));
        txt_tipoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tipoClienteActionPerformed(evt);
            }
        });

        txt_tipomovi.setEditable(false);
        txt_tipomovi.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        txt_tipomovi.setForeground(new java.awt.Color(255, 153, 51));
        txt_tipomovi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tipomoviActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel8.setText("Tipo de cliente:");

        btn_balance.setFont(new java.awt.Font("Yu Gothic", 3, 14)); // NOI18N
        btn_balance.setForeground(new java.awt.Color(255, 153, 0));
        btn_balance.setText("Mostar Balance");
        btn_balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_balanceActionPerformed(evt);
            }
        });

        dexc.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        dexc.setText("Descripción:");

        txt_des.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        txt_des.setForeground(new java.awt.Color(255, 153, 51));
        txt_des.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_desActionPerformed(evt);
            }
        });

        jbc_te.setFont(new java.awt.Font("Verdana", 3, 18)); // NOI18N
        jbc_te.setForeground(new java.awt.Color(255, 153, 0));
        jbc_te.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Debe", "Haber" }));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel9.setText("Tipo de movimiento:");

        txt_tipoCuenta.setEditable(false);
        txt_tipoCuenta.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        txt_tipoCuenta.setForeground(new java.awt.Color(255, 153, 51));
        txt_tipoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tipoCuentaActionPerformed(evt);
            }
        });

        jLabel10.setText("Neil Otniel Moreno Rivera");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(48, 48, 48)
                                .addComponent(txt_tipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(49, 49, 49)
                                .addComponent(txt_tipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_asientoContable, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(btn_balance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbc_te, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_tipomovi, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 215, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(dexc)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel3)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_cliente1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                            .addComponent(txt_des)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_interes, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcb_tipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbl_error, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dexc)
                    .addComponent(txt_des, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_tipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_cliente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbc_te, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_interes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_tipomovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_tipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_asientoContable, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_balance)
                        .addGap(34, 34, 34)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbl_error, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cuentaActionPerformed
     try{
       cuenta[cont]=new CbancoActivo();
                cuenta[cont].setCuenta(Integer.parseInt(txt_cuenta.getText()));
                cuenta[cont].setCliente(Integer.parseInt(txt_cliente1.getText()));
                cuenta[cont].setSaldo(Float.parseFloat(txt_saldo.getText()));
                cuenta[cont].setInteres(Float.parseFloat(txt_interes.getText()));
                cuenta[cont].setTipo_de_cuenta(txt_tipoCliente.getText());
                txt_tipoCliente.setText(cuenta[cont].getTipo_de_Cliente());
                jta_salida.setText(cuenta[cont].mostrar());
     }
     catch(NumberFormatException e){
         jbl_error.setText("El valor debe de ser numerico");
     }
     catch(CbancoExcepcion e){
         jbl_error.setText(e.getMessage());
     }
     catch(Cbancoidentificador x){
         jbl_error.setText(x.getMessage());
     }
    }//GEN-LAST:event_txt_cuentaActionPerformed

    private void txt_saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_saldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_saldoActionPerformed

    private void txt_cliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cliente1ActionPerformed

    private void txt_cliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cliente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cliente2ActionPerformed

    private void txt_interesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_interesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_interesActionPerformed
    private void btn_asientoContableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_asientoContableActionPerformed
         jbl_error.setText("");
        txt_tipoCuenta.setText(jcb_tipoCuenta.getSelectedItem()+"");
        try{
            if(txt_tipoCuenta.getText().equals("Activo")){
                cuenta[cont]=new CbancoActivo();
                cuenta[cont].setCuenta(Integer.parseInt(txt_cuenta.getText()));
                cuenta[cont].setCliente(Integer.parseInt(txt_cliente1.getText()));
                cuenta[cont].setSaldo(Float.parseFloat(txt_saldo.getText()));
                cuenta[cont].setInteres(Float.parseFloat(txt_interes.getText()));
                cuenta[cont].setTipo_de_cuenta(txt_tipoCliente.getText());
                cuenta[cont].setEspe(txt_des.getText());
                txt_tipoCliente.setText(cuenta[cont].getTipo_de_Cliente());
                txt_tipomovi.setText(jbc_te.getSelectedItem()+"");
                cuenta[cont].setMovi(txt_tipomovi.getText());
                cuenta[cont].setTipo_de_cuenta(txt_tipoCuenta.getText());
                jta_salida.setText(cuenta[cont].mostrar());  
                jbl_error.setText("Cuenta de activo creada"); 
                cont++;
            }else if(txt_tipoCuenta.getText().equals("Pasivo")){
               cuenta[cont]=new CbancoPasivo(); 
                cuenta[cont].setCuenta(Integer.parseInt(txt_cuenta.getText()));
                cuenta[cont].setCliente(Integer.parseInt(txt_cliente1.getText()));
                cuenta[cont].setSaldo(Float.parseFloat(txt_saldo.getText()));
                cuenta[cont].setInteres(Float.parseFloat(txt_interes.getText()));
                cuenta[cont].setTipo_de_cuenta(txt_tipoCliente.getText());
                cuenta[cont].setEspe(txt_des.getText());
                txt_tipoCliente.setText(cuenta[cont].getTipo_de_Cliente());
                txt_tipomovi.setText(jbc_te.getSelectedItem()+"");
                cuenta[cont].setMovi(txt_tipomovi.getText());
                cuenta[cont].setTipo_de_cuenta(txt_tipoCuenta.getText());
                jta_salida.setText(cuenta[cont].mostrar());                        
                jbl_error.setText("Cuenta de pasivo creada"); 
                cont++;
                
            }else if(txt_tipoCuenta.getText().equals("Capital")){
                cuenta[cont]=new CbancoCapital();
                cuenta[cont].setCuenta(Integer.parseInt(txt_cuenta.getText()));
                cuenta[cont].setCliente(Integer.parseInt(txt_cliente1.getText()));
                cuenta[cont].setSaldo(Float.parseFloat(txt_saldo.getText()));
                cuenta[cont].setInteres(Float.parseFloat(txt_interes.getText()));
                cuenta[cont].setTipo_de_cuenta(txt_tipoCliente.getText());
                cuenta[cont].setEspe(txt_des.getText());
                txt_tipoCliente.setText(cuenta[cont].getTipo_de_Cliente());
                txt_tipomovi.setText(jbc_te.getSelectedItem()+"");
                cuenta[cont].setMovi(txt_tipomovi.getText());
                cuenta[cont].setTipo_de_cuenta(txt_tipoCuenta.getText());
                jta_salida.setText(cuenta[cont].mostrar());
                jta_salida.setText(cuenta[cont].mostrar());
                jbl_error.setText("Cuenta de capital creada"); 
                cont++;
            }
            
        
        }catch(NumberFormatException e){
            jbl_error.setText("El valor debe ser numerico");
        }
        catch(CbancoExcepcion e){
            jbl_error.setText(e.getMessage());
        }
        catch(ArrayIndexOutOfBoundsException e){
            jbl_error.setText("Está fuera del arreglo");
        } catch (Cbancoidentificador ex) {
            jbl_error.setText("Comprobar cliente");
        }
    }//GEN-LAST:event_btn_asientoContableActionPerformed

    private void jcb_tipoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_tipoCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_tipoCuentaActionPerformed

    private void txt_tipoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tipoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tipoClienteActionPerformed

    private void txt_tipomoviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tipomoviActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tipomoviActionPerformed

    private void btn_balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_balanceActionPerformed
              String salida=""; 

        for(int i=0; i<20;i++){
            if(cuenta[i]!=null){
        salida=salida+cuenta[i].toString();
            if (cuenta[i].getTipo_de_cuenta().equals("Activo")){
                    if(cuenta[i].getMovi().equals("Debe")){
                        activo=activo+cuenta[i].getSaldo();
                     }
                     if(cuenta[i].getMovi().equals("Haber")){
              activo=activo-cuenta[i].getSaldo();
             }
            }
            if (cuenta[i].getTipo_de_cuenta().equals("Pasivo")){
                   if(cuenta[i].getMovi().equals("Debe")){
                        pasivo=pasivo-cuenta[i].getSaldo();
                     }else{
                     if(cuenta[i].getMovi().equals("Haber")){
              pasivo=pasivo+cuenta[i].getSaldo();
             }
            }}
            if (cuenta[i].getTipo_de_cuenta().equals("Capital")){
                 if(cuenta[i].getMovi().equals("Debe")){
                        capital=capital-cuenta[i].getSaldo();
                     }else{
                     if(cuenta[i].getMovi().equals("Haber")){
              capital=capital+cuenta[i].getSaldo();
             }}
            }
        }    
        }
        if(activo==(pasivo+capital)){
            salida=salida+ "\n"+"El balance cuadra"+"\nActivo:"+activo+"\nPasivo:"+pasivo+"\n Capital:"+capital ;
        }else{
            salida=salida+"\n"+"El balance no cuadra"+"\nActivo:"+activo+"\nPasivo:"+pasivo+"\n Capital:"+capital;
        }
        jta_salida.setText(salida);
    }//GEN-LAST:event_btn_balanceActionPerformed

    private void txt_desActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_desActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_desActionPerformed

    private void txt_tipoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tipoCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tipoCuentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRNBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRNBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRNBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRNBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRNBanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_asientoContable;
    private javax.swing.JButton btn_balance;
    private javax.swing.JLabel dexc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jbc_te;
    public javax.swing.JLabel jbl_error;
    private javax.swing.JComboBox<String> jcb_tipoCuenta;
    private javax.swing.JTextArea jta_salida;
    private javax.swing.JTextField txt_cliente1;
    private javax.swing.JTextField txt_cliente2;
    private javax.swing.JTextField txt_cuenta;
    private javax.swing.JTextField txt_cuenta1;
    private javax.swing.JTextField txt_des;
    private javax.swing.JTextField txt_interes;
    private javax.swing.JTextField txt_saldo;
    private javax.swing.JTextField txt_tipoCliente;
    private javax.swing.JTextField txt_tipoCuenta;
    private javax.swing.JTextField txt_tipomovi;
    // End of variables declaration//GEN-END:variables

    private void jbl_identificador(String cliente_nacional) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
